name: Generate rules

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'
    - cron: '*/5 * * * *'

jobs:
  scheduled-job:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm install
      - run: npm start
      - run: cat rules.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            # Optional. Commit message for the created commit.
            # Defaults to "Apply automatic changes"
            commit_message: Update rules
            branch: master
            file_pattern: 'rules.json'
            disable_globbing: true